### ISSUE TITLE
Regarding Debatepedia Dataset

### ISSUE THREAD

**Issue by tahmedge** [talbaumel/RSAsummarization#1]
Did you convert the text dataset into binary format like the Pointer Generation paper's code? 
If so, can you provide me the code to convert the Debatepedia Dataset to Binary format so that it can work in your code?

**Comment by talbaumel** [comment]
Hi, I used code provided by https://github.com/abisee

**Comment by tahmedge** [comment]
Hi, Since in the Pointer Generation Paper they used different dataset and the dataset was converted to Binary format, did you also converted your dataset for Gigaword to Binary format ?

**Comment by talbaumel** [comment]
We didn’t use the gigaword dataset either. Only DUC07

**Comment by tahmedge** [comment]
I am sorry for my mistake. It should be the "Debatepedia" dataset instead of "Gigaword".

**Comment by talbaumel** [comment]
We formatted it to daily-mail/cnn format and used Abigail’s code

**Comment by tahmedge** [comment]
Thanks a lot. :) Will the your converted binary formatted version of Debatepedia dataset be released ?

**Comment by talbaumel** [comment]
Sorry, I don’t have access to server’s used for it anymore

**Comment by tahmedge** [comment]
Oh. Thanks.

**Comment by tahmedge** [comment]
Hi, I have another query. In the original PointerGenerationNetwork code, we need to run the run_summarization.py for training. Here, which file should we run for query focused summarization training?

**Comment by talbaumel** [comment]
Same

**Comment by tahmedge** [comment]
Thanks for your reply. Can you please tell me what is the purpose of "kl_qcfs.py" and "runsum.py" code ?

**Comment by tahmedge** [comment]
Thanks for your reply. Can you please tell me what is the purpose of "kl_qcfs.py", "runsum.py", "runvis.py" and their differences ?

Also, while making the binary version of the dataset, did you save the "Article" "Abstract" and "Relevance" score in the binarized dataset? Based on reading your code, I guess you saved the "Relevance" score instead of "Queries".

**Comment by tahmedge** [comment]
Thanks for your reply. Can you please tell me what is the purpose of "kl_qcfs.py", "runsum.py", "runvis.py" and their differences ?

Also, while making the binary version of the dataset, did you save the "Article" "Abstract" and "Relevance" score in the binarized dataset? Based on reading your code, I guess you saved the "Relevance" score instead of "Queries".

**Comment by talbaumel** [comment]
I might be wrong :
- "kl_qcfs.py" for running the iterative version with kl divergence to avoid redundancy.
- "runsum.py" run the single doc version.
-  "runvis.py" HTML attention visualizer.

I don't remember the details about the binary files format, sorry :(

**Comment by tahmedge** [comment]
Thank you very much.
