### ISSUE TITLE
Model output for debatepedia

### ISSUE THREAD

**Issue by TysonYu** [talbaumel/RSAsummarization#3]
Hi there,

Thanks for publishing the code and the produced summaries. In the dev/dec, I can find some summary but not sure whether it is generated from Debatepedia. 

I try to do human evaluation for the produced summaries but can not find the documents and query for the summaries. 
Can I get a version that the summary is aligning with the documents and queries?

Thank you very much!

Best Regards,
Tyson

**Comment by talbaumel** [comment]
Hi Tyson,
I'm sorry but since graduating I didn't renew my access to the university
servers.
I can't help you :(

Sorry, Tal

**Comment by TysonYu** [comment]
Sure, I can understand.
Thanks for your quick reply!

Tyson
